version: 2.1

aliases:
  - &default_env
  - &all

jobs:
  main:
    environment:
      - *default_env
    docker:
      - image: hogeyama/fpat-dependencies
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "ca:7c:6d:b5:3d:a8:c7:5c:d4:38:1e:3a:05:3f:59:0a"
      - run:
          name: Build fpat
          command: |
            eval $(opam env)
            if [ -d $HOME/depend/mochi-for-fpat ]
            then
              echo "cached"
            else
              ssh-agent bash -c \
                'ssh-add $HOME/.ssh/id_rsa_ca7c6db53da8c75cd4381e3a053f590a; \
                 git clone git@bitbucket.org:ryosu_sato/mochi $HOME/depend/mochi-for-fpat'
            fi
            cd $HOME/depend/mochi-for-fpat
            git checkout b889e4e572d6792b0c9ddd0c5561bc8c4d90271e
            cd $HOME/depend/mochi-for-fpat/csisat
            make lib
            cd $HOME/depend/mochi-for-fpat/fpat
            ./configure
            patch < $HOME/project/.circleci/fpat-for-4.0.6.patch
            make install-lib
            make
            make install
      - run:
          name: Install direct dependencies
          command: |
            # TODO better practice
            opam install oUnit re2
      - run:
          name: Install horsat2
          command: |
            # TODO better practice
            sudo install $HOME/project/.circleci/horsat2 /bin
      - run:
          name: Build
          command: |
            eval $(opam env)
            cd $HOME/project
            dune build
      - run:
          name: Run test
          command: |
            eval $(opam env)
            cd $HOME/project
            dune runtest

workflows:
  version: 2
  all:
    jobs:
      - main
