---
name: docker build

on:
  push:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          load: true
          push: true
          target: build
          cache-from: type=registry,ref=hogeyama/hflmc2:build
          cache-to: type=inline
          tags: hogeyama/hflmc2:build

      - name: Test
        run:  docker run --rm hogeyama/hflmc2:build opam exec -- dune runtest

      - name: Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: hogeyama/hflmc2:latest
